### ISSUE TITLE
✨ Create data table

### ISSUE THREAD

**Issue by Junnyyy** [CougarCS/CougarCS-AdminPortal#16]
Create a modular table that can receive columns and data.

Ideally prep future capability to have a modal popup when clicking on row.

Design:
```jsx
import { Table } from '@mantine/core';

function Demo({columns, data}) {
  return (
    <Table highlightOnHover>
      {/* {...rows} */}
    </Table>
  );
}
```

![image](https://user-images.githubusercontent.com/44646589/213291168-a279b92b-1764-4180-b659-6dc34de01295.png)

**Comment by seesjays** [comment]
Used [Tailwind's \@apply function](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply) to make a style wrapper akin to what Mantine is probably doing. The \@apply's are in the `globals.css` file and only affect tables with the `data-table` class

## Now the table can be used for anything you make the columns and headers for.
<img width="484" alt="Screen Shot 2023-01-19 at 11 29 25 PM" src="https://user-images.githubusercontent.com/39662993/213626899-6132a086-fa8d-4680-967a-20cacbfe7788.png">

### It also works without headers if needed
Have to somehow fix the padding for this case though
<img width="223" alt="Screen Shot 2023-01-19 at 11 31 38 PM" src="https://user-images.githubusercontent.com/39662993/213627038-2a35d593-25f4-4b6a-a71b-2d51cc4cacad.png">

## Added it to the members page as well
Just for the sake of testing
<img width="1624" alt="Screen Shot 2023-01-19 at 11 53 54 PM" src="https://user-images.githubusercontent.com/39662993/213627137-e7f89322-d74b-46a6-b38c-0cf8399b68ee.png">
