### ISSUE TITLE
Fix DataTable styling

### ISSUE THREAD

**Issue by seesjays** [CougarCS/CougarCS-AdminPortal#26]
Our current data table, found in `/components/dataTable/dataTable` is from a very early build and doesn't match the new design we have.

### Current
<img width="956" alt="image" src="https://user-images.githubusercontent.com/39662993/230494246-3bb4a7d4-8efb-42ef-b41c-2b6eca3e9801.png">

### Target
<img width="872" alt="image" src="https://user-images.githubusercontent.com/39662993/230494346-b7e634af-1084-4111-a560-b6c3797a1398.png">

Heavily tweak the tailwind classnames in the dataTable component so that it matches the new design visually. This mostly involves removing all the borders, making the heading text left aligned instead of centered, and adding a background color to the headings.

**Comment by JadenJT** [comment]
Done boom
