### ISSUE TITLE
Redesign log out button

### ISSUE THREAD

**Issue by Brodypen** [CougarCS/CougarCS-AdminPortal#53]
Currently, our log-out button on the sidebar looks like this.
<img width="226" alt="image" src="https://user-images.githubusercontent.com/45112852/233724275-d8fb2851-8fc4-4b56-907a-e915f560572a.png">

However, we want it to look like this!
<img width="153" alt="image" src="https://user-images.githubusercontent.com/45112852/233724203-f69a03de-de0d-4d12-847a-eeb70aec63fd.png">

Fix this disharmony, and use FaSignOutAlt for the icon!

**Comment by seesjays** [comment]
Also make the text red please.
